# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
                    - nama: Tutup Masalah yang Sudah Kadaluarsa
  penggunaan: actions/stale@v10.2.0
  dengan:
    # Token untuk repositori. Dapat diberikan menggunakan `{{ secrets.GITHUB_TOKEN }}`
    token repositori: # opsional, defaultnya adalah ${{ github.token }}
    # Pesan yang akan diposting pada isu saat memberi tag. Jika tidak ada yang diberikan, isu tidak akan ditandai sebagai usang.
    pesan-masalah-usang: # opsional
    # Pesan yang akan diposting pada pull request saat memberi tag. Jika tidak ada yang diberikan, pull request tidak akan ditandai sebagai usang.
    stale-pr-message: # opsional
    # Pesan yang akan diposting pada isu saat menutupnya. Jika tidak ada yang diberikan, tidak akan ada komentar saat menutup isu.
    close-issue-message: # opsional
    # Pesan yang akan diposting pada pull request saat ditutup. Jika tidak ada yang diberikan, tidak akan ada komentar saat menutup pull request.
    close-pr-message: # opsional
    # Jumlah hari sebuah isu atau permintaan pull dapat ditandai sebagai usang. Atur ke -1 untuk tidak pernah menandai isu atau permintaan pull sebagai usang secara otomatis.
    hari-sebelum-basi: # opsional, defaultnya adalah 60
    # Jumlah hari suatu isu boleh dianggap usang sebelum ditandai sebagai tidak relevan. Atur ke -1 untuk tidak pernah menandai isu sebagai usang secara otomatis. Mengesampingkan opsi "hari-sebelum-usang" hanya untuk isu-isu tersebut.
    hari-sebelum-masalah-kadaluarsa: # opsional
    # Jumlah hari usia pull request sebelum ditandai sebagai usang. Atur ke -1 untuk tidak pernah menandai pull request sebagai usang secara otomatis. Mengesampingkan opsi "days-before-stale" hanya untuk pull request.
    hari-sebelum-pr-usang: # opsional
    # Jumlah hari untuk menunggu sebelum menutup sebuah issue atau pull request setelah ditandai sebagai usang. Atur ke -1 untuk tidak pernah menutup issue atau pull request yang usang.
    hari-sebelum-tutup: # opsional, defaultnya adalah 7
    # Jumlah hari yang harus ditunggu sebelum menutup sebuah isu setelah ditandai sebagai usang. Atur ke -1 untuk tidak pernah menutup isu usang. Mengesampingkan opsi "hari-sebelum-penutupan" hanya untuk isu-isu tersebut.
    hari-sebelum-penutupan-masalah: # opsional
    # Jumlah hari yang ditunggu sebelum menutup permintaan pull setelah ditandai sebagai usang. Atur ke -1 untuk tidak pernah menutup permintaan pull yang usang. Mengesampingkan opsi "days-before-close" hanya untuk permintaan pull.
    hari-sebelum-penutupan-pers: # opsional
    # Label yang akan diterapkan ketika suatu isu sudah usang.
    label-masalah-usang: # opsional, defaultnya adalah Usang
    # Label yang akan diterapkan saat sebuah isu ditutup.
    label-tutup-masalah: # opsional
    # Label yang menandakan suatu isu dikecualikan dari penandaan sebagai isu usang. Pisahkan beberapa label dengan koma (misalnya, "label1,label2").
    exempt-issue-labels: # opsional, defaultnya adalah
    # Alasan untuk digunakan saat menutup sebuah isu.
    close-issue-reason: # opsional, defaultnya adalah not_planned
    # Label yang akan diterapkan ketika sebuah pull request dianggap usang.
    stale-pr-label: # opsional, defaultnya adalah Stale
    # Label yang akan diterapkan saat permintaan pull ditutup.
    close-pr-label: # opsional
    # Label yang menandakan bahwa pull request dikecualikan dari penandaan sebagai usang. Pisahkan beberapa label dengan koma (misalnya, "label1,label2").
    exempt-pr-labels: # opsional, defaultnya adalah
    # Tonggak pencapaian yang menandakan suatu masalah atau permintaan perubahan (pull request) dikecualikan dari penandaan sebagai usang. Pisahkan beberapa tonggak pencapaian dengan koma (misalnya, "milestone1,milestone2").
    exempt-milestones: # opsional, defaultnya adalah
    # Tonggak pencapaian yang menandakan suatu isu dikecualikan dari penandaan sebagai usang. Pisahkan beberapa tonggak pencapaian dengan koma (misalnya, "milestone1,milestone2"). Timpa opsi "exempt-milestones" hanya untuk isu-isu tersebut.
    exempt-issue-milestones: # opsional, defaultnya adalah
    # Tonggak pencapaian yang menandakan permintaan pull request dikecualikan dari penandaan sebagai usang. Pisahkan beberapa tonggak pencapaian dengan koma (misalnya, "milestone1,milestone2"). Timpa opsi "exempt-milestones" hanya untuk permintaan pull request.
    exempt-pr-milestones: # opsional, defaultnya adalah
    # Kecualikan semua isu dan permintaan pull dengan milestone agar tidak ditandai sebagai usang. Nilai default adalah false.
    exempt-all-milestones: # opsional, defaultnya false
    # Kecualikan semua isu dengan pencapaian penting agar tidak ditandai sebagai usang. Timpa opsi "exempt-all-milestones" hanya untuk isu-isu tersebut.
    exempt-all-issue-milestones: # opsional, defaultnya adalah
    # Kecualikan semua permintaan pull dengan milestone agar tidak ditandai sebagai usang. Timpa opsi "exempt-all-milestones" hanya untuk permintaan pull tersebut.
    exempt-all-pr-milestones: # opsional, defaultnya adalah
    # Hanya isu atau permintaan pull dengan semua label ini yang diperiksa apakah sudah usang. Nilai defaultnya adalah `` (dinonaktifkan) dan dapat berupa daftar label yang dipisahkan koma.
    hanya-label: # opsional, defaultnya adalah
    # Hanya isu atau permintaan pull dengan setidaknya satu label ini yang diperiksa apakah sudah usang. Nilai defaultnya adalah `` (dinonaktifkan) dan dapat berupa daftar label yang dipisahkan koma.
    any-of-labels: # opsional, defaultnya adalah
    # Hanya masalah dengan setidaknya satu dari label ini yang diperiksa jika sudah usang. Nilai defaultnya adalah `` (dinonaktifkan) dan dapat berupa daftar label yang dipisahkan koma. Ganti opsi "any-of-labels" hanya untuk masalah-masalah tersebut.
    any-of-issue-labels: # opsional, defaultnya adalah
    # Hanya permintaan pull dengan setidaknya satu label ini yang diperiksa apakah sudah usang. Nilai defaultnya adalah `` (dinonaktifkan) dan dapat berupa daftar label yang dipisahkan koma. Mengesampingkan opsi "any-of-labels" hanya untuk permintaan pull.
    any-of-pr-labels: # opsional, defaultnya adalah
    # Hanya masalah dengan semua label ini yang diperiksa apakah sudah usang. Defaultnya adalah `[]` (dinonaktifkan) dan dapat berupa daftar label yang dipisahkan koma. Mengganti opsi "only-labels" hanya untuk masalah-masalah tersebut.
    only-issue-labels: # opsional, defaultnya adalah
    # Hanya permintaan pull dengan semua label ini yang diperiksa apakah sudah usang. Defaultnya adalah `[]` (dinonaktifkan) dan dapat berupa daftar label yang dipisahkan koma. Mengganti opsi "only-labels" hanya untuk permintaan pull.
    only-pr-labels: # opsional, defaultnya adalah
    # Jumlah maksimum operasi per eksekusi, digunakan untuk mengontrol pembatasan laju (terkait CRUD API GitHub).
    operasi per eksekusi: # opsional, defaultnya adalah 30
    # Hapus label usang dari isu dan permintaan pull saat diperbarui atau dikomentari.
    remove-stale-when-updated: # opsional, defaultnya adalah true
    # Hapus label usang dari isu ketika isu tersebut diperbarui atau dikomentari. Timpa opsi "remove-stale-when-updated" hanya untuk isu-isu tersebut.
    remove-issue-stale-when-updated: # opsional, defaultnya adalah
    # Hapus label usang dari permintaan pull saat diperbarui atau dikomentari. Timpa opsi "remove-stale-when-updated" hanya untuk permintaan pull.
    remove-pr-stale-when-updated: # opsional, defaultnya adalah
    # Jalankan prosesor dalam mode debug tanpa benar-benar melakukan operasi apa pun pada masalah yang sedang berjalan.
    Hanya untuk debugging: # opsional, defaultnya adalah false
    # Urutan untuk mendapatkan isu atau permintaan pull. Secara default bernilai false, yang berarti urutan menurun.
    ascending: # opsional, defaultnya false
    # Kriteria pengurutan hasil. Opsi yang valid adalah `created`, `updated`, dan `comments`. Defaultnya adalah `created`.
    Urutkan berdasarkan: # opsional, defaultnya adalah dibuat
    # Hapus cabang git setelah menutup permintaan pull yang sudah usang.
    hapus-cabang: # opsional, defaultnya false
    # Tanggal yang digunakan untuk melewati tindakan usang pada isu/permintaan tarik yang dibuat sebelum tanggal tersebut (ISO 8601 atau RFC 2822).
    tanggal-mulai: # opsional, defaultnya adalah
    # Para penerima tugas yang mengecualikan suatu isu atau permintaan pull dari penandaan sebagai usang. Pisahkan beberapa penerima tugas dengan koma (misalnya, "user1,user2").
    exempt-assignees: # opsional, defaultnya adalah
    # Penerima tugas yang mengecualikan suatu masalah agar tidak ditandai sebagai usang. Pisahkan beberapa penerima tugas dengan koma (misalnya, "user1,user2"). Timpa opsi "exempt-assignees" hanya untuk masalah-masalah tersebut.
    exempt-issue-assignees: # opsional, defaultnya adalah
    # Penerima tugas yang mengecualikan permintaan pull agar tidak ditandai sebagai usang. Pisahkan beberapa penerima tugas dengan koma (misalnya, "user1,user2"). Timpa opsi "exempt-assignees" hanya untuk permintaan pull.
    exempt-pr-assignees: # opsional, defaultnya adalah
    # Kecualikan semua isu dan permintaan pull dengan penanggung jawab agar tidak ditandai sebagai usang. Nilai default adalah false.
    exempt-all-assignees: # opsional, defaultnya false
    # Kecualikan semua masalah dengan penerima tugas agar tidak ditandai sebagai usang. Timpa opsi "exempt-all-assignees" hanya untuk masalah-masalah tersebut.
    exempt-all-issue-assignees: # opsional, defaultnya adalah
    # Kecualikan semua permintaan pull dengan penerima tugas agar tidak ditandai sebagai usang. Timpa opsi "exempt-all-assignees" hanya untuk permintaan pull.
    exempt-all-pr-assignees: # opsional, defaultnya adalah
    # Kecualikan draf permintaan pull agar tidak ditandai sebagai usang. Nilai default adalah false.
    exempt-draft-pr: # opsional, defaultnya false
    # Tampilkan beberapa statistik di akhir terkait alur kerja yang usang (hanya jika log diaktifkan).
    enable-statistics: # opsional, defaultnya adalah true
    # Daftar label yang dipisahkan koma untuk ditambahkan ketika sebuah isu atau permintaan pull request menjadi tidak usang.
    labels-to-add-when-unstale: # opsional, defaultnya adalah
    # Daftar label yang dipisahkan koma untuk dihapus ketika sebuah isu atau permintaan pull request menjadi usang.
    label yang akan dihapus saat sudah usang: # opsional, defaultnya adalah
    # Daftar label yang dipisahkan koma untuk dihapus ketika sebuah isu atau permintaan pull request menjadi tidak relevan.
    label yang akan dihapus saat tidak lagi berlaku: # opsional, defaultnya adalah
    # Setiap pembaruan (update/komentar) dapat mengatur ulang waktu idle yang kedaluwarsa pada isu dan permintaan pull.
    ignore-updates: # opsional, defaultnya false
    # Setiap pembaruan (update/komentar) dapat mengatur ulang waktu idle yang kedaluwarsa pada isu. Timpa opsi "ignore-updates" hanya untuk isu-isu tersebut.
    ignore-issue-updates: # opsional, defaultnya adalah
    # Setiap pembaruan (update/komentar) dapat mengatur ulang waktu idle yang kedaluwarsa pada permintaan pull. Timpa opsi "ignore-updates" hanya untuk permintaan pull.
    ignore-pr-updates: # opsional, defaultnya adalah
    # Hanya isu atau permintaan pull yang memiliki penanggung jawab yang akan ditandai sebagai usang secara otomatis.
    include-only-assigned: # opsional, defaultnya false
    # Hanya masalah dengan tipe yang cocok yang diproses sebagai usang/tertutup. Secara default menggunakan `[]` (dinonaktifkan) dan dapat berupa daftar tipe masalah yang dipisahkan koma.
    tipe-masalah-saja: # opsional, defaultnya adalah
          
